version: "3"

services:
  api:
    build: .
    container_name: rust_api_api
    command: ./rust-api
    ports:
      - 3333:3333
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: rust_api_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432